### ISSUE TITLE
Is it possible to select multiple days programatically and disable selection via touch?

### ISSUE THREAD

**Issue by plastus** [n8armstrong/CalendarView#14]
Hi,

I'm looking for a way to select multiple days programatically and to disable the ability for the user to select dates on their own via touch. Is this possible using the framework? When I use the selectDate method it clears the previous selection's highlight for that particular date.

Also, curious whether the extent to which a user can scroll can be limited. For example, no earlier than January, 2015.

Thank you in advance!

**Comment by armstrongnate** [comment]
Those features should not be too difficult to implement but I probably won't implement them myself. You are welcome to fork and create a pull request.
