### ISSUE TITLE
two November 6th dates in November 2016 cal

### ISSUE THREAD

**Issue by mikeh0rn** [n8armstrong/CalendarView#16]
Similar issue as https://github.com/n8armstrong/CalendarView/issues/7 but this time displaying two November 6 dates, pushing each date up 1 day.

**Comment by plastus** [comment]
Are you running the latest release? I checked this with 1.1.2 and November 2016 renders without issue.

**Comment by mikeh0rn** [comment]
@plastus what is the latest release? my podfile is:
`pod 'CalendarView', '~> 1.1.2'`

my Podfile.lock displays:
`- CalendarView (1.1.2):
    - SwiftMoment (~> 0.1)`

**Comment by mikeh0rn** [comment]
@plastus @n8armstrong screenshot of the CalenderViewDemo included in the github repo:

![image1](https://cloud.githubusercontent.com/assets/8358047/17564504/7e9847e0-5f01-11e6-8223-c1309a1c02e9.PNG)

**Comment by plastus** [comment]
My file:

PODS:
- CalendarView (1.1.2):
- SwiftMoment (0.5.1)

Can you confirm whether you're seeing the issue with those versions of CalendarView and SwiftMoment?

**Comment by mikeh0rn** [comment]
@plastus @n8armstrong I'm seeing the issue in my own project which is using:
`CalendarView (1.1.2): 
SwiftMoment (~> 0.1)`

The CalendarView demo included in the CalendarView repo has the following in Podfile.lock:

`````` PODS:
  - CalendarView (1.1.0):
    - SwiftMoment (~> 0.1)
  - SwiftMoment (0.3)```
``````

**Comment by plastus** [comment]
@mikeh0rn Run 'pod update SwiftMoment' from your terminal and see if the issue goes away.

**Comment by mikeh0rn** [comment]
@plastus that worked. thank you.

**Comment by plastus** [comment]
@mikeh0rn Glad everything's fixed. :)

**Comment by armstrongnate** [comment]
Thanks @plastus
