### ISSUE TITLE
Migrating project to Swift 3

### ISSUE THREAD

**Issue by AileenMoreno** [n8armstrong/CalendarView#20]
Hi, 

i've been trying to migrate my project to Swift 3 .  I've been using CalendarView and SwiftMoment as pods, but since migration i've been fighting with these error :

"../Pods/CalendarView/CalendarView/CalendarView/Classes/CalendarView.swift:10:8: Module file's minimum deployment target is ios9.0 v9.0: .../Library/Developer/Xcode/DerivedData/...-bembwssqhwzpjxfaxhkaiirqpxoy/Build/Products/Debug-iphonesimulator/SwiftMoment/SwiftMoment.framework/Modules/SwiftMoment.swiftmodule/x86_64.swiftmodule"

This is my podfile

platform :ios, '9.0'
use_frameworks!

def shared_pods
  pod 'SwiftDate', '4.0.12'
  pod 'SwiftMoment', '0.7'
  pod 'SwiftyJSON', '3.1.4'
  pod 'XCGLogger', '4.0.0'
end

def app_pods
  pod 'Alamofire', '4.0.1'
  pod 'BNHtmlPdfKit', '0.4.2'
  pod 'CalendarView', '1.1.2'
  pod 'MonthYearPicker', '1.0.0'
  pod 'SideMenu', '2.2.0'
  pod 'SwiftyDropbox', '4.1.1'
  pod 'Zip', '0.6.0'
  pod 'MBProgressHUD', '1.0.0'
  pod 'Fabric', '1.6.11'
  pod 'Crashlytics','3.8.3'
end

Also i tried changing SwiftMoment to 0.3

What can i do?

Thanks

**Comment by AileenMoreno** [comment]
Module compiled with Swift 2.3 cannot be imported in Swift 3.0.1: .../Library/Developer/Xcode/DerivedData/...r-bembwssqhwzpjxfaxhkaiirqpxoy/Build/Products/Debug-iphonesimulator/SwiftMoment/SwiftMoment.framework/Modules/SwiftMoment.swiftmodule/x86_64.swiftmodule

**Comment by webtesting2018** [comment]
Module file's minimum deployment target is ios9.0 v9.0: /Users/macbook/Desktop/Jaydev/DeriveData/Debug-iphonesimulator/SwiftMoment/SwiftMoment.framework/Modules/SwiftMoment.swiftmodule/x86_64.swiftmodule

**Comment by Maximelc** [comment]
Hi,

I fix this problem!
It will be fixed when the issue https://github.com/n8armstrong/CalendarView/issues/21 will be closed.

I can explain my solution if need 😇

**Comment by umarfarooq21** [comment]
@Maximelc can you please describe me the solution i having same issue.

**Comment by armstrongnate** [comment]
It's been updated to swift 4 here https://github.com/armstrongnate/CalendarView/pull/22
