### ISSUE TITLE
Swift 4 compatibility + linking error with SwiftMoment

### ISSUE THREAD

**Issue by Maximelc** [n8armstrong/CalendarView#21]
Hi,

When i tried to install this pod, after compilation I've got this error :
`error: module file's minimum deployment target is ios9.0 v9.0`
for the file *CalendarView.swift* at the ligne of the import of SwiftMoment pod.

So i find a solution to fix this problem, and by the same occasion i put the Swift 4+ compatibility!

If interested, i can make a PR with the updated code and the fixes.

Merci.

**Comment by paultwin0202** [comment]
Please updated code. It would be great for me

**Comment by michaelcordero** [comment]
Hi, @Maximelc @paultwin0202  I am getting the same error message. was this patch ever applied?

**Comment by armstrongnate** [comment]
@Maximelc feel free to open a PR with the fixes. I don't have time to work on this right now, sorry.

**Comment by umarfarooq21** [comment]
getting same error...

**Comment by Krindred** [comment]
Did you try changing the pod deployment target?

**Comment by verebes1** [comment]
I have updated it to Swift 4 hopefully will be merged soon.

**Comment by armstrongnate** [comment]
@verebes1 I merged it. Thanks.

**Comment by Beautistar** [comment]
I am facing same issue in swift 4, xcode 10.
How can I solve it?
