### ISSUE TITLE
Highlighting Specific Days

### ISSUE THREAD

**Issue by RyanDawkins** [n8armstrong/CalendarView#3]
Is it possible to highlight specific days? I haven't seen anything in the API.

**Comment by armstrongnate** [comment]
You can use the `selectDate:` method.

``` swift
var calendarView = CalendarView()
let date: NSDate = MY_NSDATE
calendarView.selectDate(moment(date))
```

You might have to call it from `viewWillAppear` or `viewDidAppear`.
