### ISSUE TITLE
Disable Vertical Movement

### ISSUE THREAD

**Issue by Treverr** [n8armstrong/CalendarView#6]
When scrolling through the dates, I can move the calendar up and down, is there anyway to disable that? Or any suggested way I'm missing in Xcode?

Thank you!

**Comment by armstrongnate** [comment]
Check to make sure `automaticallyAdjustsScrollViewInsets` is false on your view controller. You can set it in code:

``` swift
override func viewDidLoad() {
    super.viewDidLoad()
    automaticallyAdjustsScrollViewInsets = false
}
```

or in the storyboard:

![image](https://cloud.githubusercontent.com/assets/1187499/12485123/8e38b06c-c01a-11e5-839a-fc628fab7a6d.png)

**Comment by Treverr** [comment]
Awesome! The only draw back is that I don't have SMTWTF at the top like I did, is that something I need to enable somewhere?

**Comment by armstrongnate** [comment]
No you shouldn't have to enable the SMTWTF headings. How are you laying out the calendar view? In storyboard with auto layout constraints? Show me some screenshots or your code and I'll try to help.

**Comment by armstrongnate** [comment]
I'm guessing the SMTWTF is just hidden under a view above the calendar. Maybe your top constraint constant needs to be positive instead of negative or vice versa?

**Comment by Treverr** [comment]
Ah you were right, I added the Navigation bar afterwards and that hid it! Duh. Haha

**Comment by armstrongnate** [comment]
Nice. Glad you figured it out. :+1:
