### ISSUE TITLE
Missing a day in March

### ISSUE THREAD

**Issue by armstrongnate** [n8armstrong/CalendarView#7]
User reports:

> I just noticed that March is always messed up in the CalendarView.  Doesn't matter which March in which year, but it always seems to skip the first Sunday after the first full week has been rendered.

Could be related to #1.

**Comment by vindicatesociety** [comment]
+1

**Comment by armstrongnate** [comment]
I'm going to guess this has something to do February only having 28 days or 29 on leap years which this year (2016) happens to be. I am looking into it.

**Comment by armstrongnate** [comment]
I can't pin it on a leap year or February-specific bug which is good because that probably would have been a fix on SwiftMoment. I'll get the fix merged and released asap.
